### ISSUE TITLE
AdvancedShippingSetting

### ISSUE THREAD

**Issue by pradeepnew** [owebia/magento2-module-advanced-shipping-setting#11] opened 2017-01-03 11:14 UTC
Fatal error: Class 'Owebia\AdvancedSettingCore\Block\System\Config\Form\Field\AbstractField' not found in /var/www/html/app/code/Owebia/AdvancedShippingSetting/Block/System/Config/Form/Field/About.php on line 10

**Comment by owebia** [comment] 2017-01-04 09:04
Duplicate of issue #8

**Closed by owebia** 2017-01-04 09:04 UTC
