### ISSUE TITLE
White page Shipping method magento 2

### ISSUE THREAD

**Issue by lucav90** [owebia/magento2-module-advanced-shipping-setting#17] opened 2017-02-27 13:37 UTC
hi,

I have installed your magento 2 module but i have a white page in Shipping method configuration page of magento 2.
i must disable your module to user correctly configuration of magento 2.

**Comment by owebia** [comment] 2017-02-27 14:02
Hi,

How did you install the module ? Using composer ?

**Comment by lucav90** [comment] 2017-02-27 14:04
i don't have composer on my server. i can't install it.
i have used the ftp method but for all other extension works better.

how can i solve?

**Comment by owebia** [comment] 2017-02-27 14:05
You can't manually install extensions with dependencies, you must use composer.  
Regards, A.L.

**Comment by owebia** [comment] 2017-02-27 14:06
Duplicate of #8

**Comment by lucav90** [comment] 2017-02-27 14:21
how can install without composer?

**Comment by owebia** [comment] 2017-02-27 14:22
You can't

**Closed** 2017-02-27 19:45 UTC
Labels: duplicate, installation issue

**Comment by lucav90** [comment] 2017-03-01 11:43
Hi,

when i use composer to install i have this error:

Problem 1
    - owebia/magento2-module-advanced-shipping-setting 2.0.5 requires owebia/magento2-module-advanced-setting-core ^2.0.4 -> satisfiable by owebia/magento2-module-advanced-setting-core[2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - owebia/magento2-module-advanced-shipping-setting 2.0.6 requires owebia/magento2-module-advanced-setting-core ^2.0.4 -> satisfiable by owebia/magento2-module-advanced-setting-core[2.0.4, 2.0.5, 2.0.6, 2.0.7].
    - owebia/magento2-module-advanced-setting-core 2.0.7 requires magento/framework ^100.0|^100.1 -> no matching package found.
    - owebia/magento2-module-advanced-setting-core 2.0.6 requires magento/framework ^100.0 -> no matching package found.
    - owebia/magento2-module-advanced-setting-core 2.0.5 requires magento/framework ^100.0 -> no matching package found.
    - owebia/magento2-module-advanced-setting-core 2.0.4 requires magento/framework ^100.0 -> no matching package found.
    - Installation request for owebia/magento2-module-advanced-shipping-setting ^2.0.5 -> satisfiable by owebia/magento2-module-advanced-shipping-setting[2.0.5, 2.0.6].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by owebia** [comment] 2017-03-01 11:44
Hi,

Are you executing composer in the magento root directory ?

Regards,
